### ISSUE TITLE
Importation Error

### ISSUE THREAD

**Issue by A-AFTAHI** [reingart/pyfpdf#112]
i started testing the library and i got importation Error
 my code looks like this: 
#! /usr/bin/env python
from fpdf import FPDF

i got the following ERROR: 

Traceback (most recent call last):
  File "./fpdf.py", line 2, in <module>
    from fpdf import FPDF
  File "/root/fpdf.py", line 2, in <module>
    from fpdf import FPDF
ImportError: cannot import name FPDF

i'm using python 2.7 on ubuntu machine.
i notice that after installing fpdf using pip the packages are stored in : /usr/local/lib/python2.7/dist-packages

**Comment by A-AFTAHI** [comment]
i was naming my script fpdf. Sorry
