### ISSUE TITLE
No such file or directory for font file.

### ISSUE THREAD

**Issue by selevanm** [reingart/pyfpdf#127]
I am loading a font file by name using the default FPDF_FONT_DIR location.  The file gets loaded properly and execution continues until I am ready to write the pdf.  After output() is called there are some other cleanup functions it appears that get called but there is a file not found error being generated in ttfonts.py at makeSubset().  I cannot access that filename so I am not sure how to resolve, below is the traceback.

Traceback (most recent call last):
  File "AutoGiftLoad.py", line 70, in main
    num_of_batches = __process_imodules_gift_data(env, path_to_reports, loader_handler, dw, process_date)
  File "AutoGiftLoad.py", line 345, in __process_imodules_gift_data
    dw.output_imodules_advance_raw_data_no_matching_pdf(searchable_members, insert_gifts, date_to_process, path_to_reports, batch_num)
  File "/usr/local/home/campuscall/automated/gift_auto_load/DataWarehouse.py", line 2151, in output_imodules_advance_raw_data_no_matching_pdf
    pdf.output(file_name, 'F')
  File "/usr/local/home/campuscall/automated/gift_auto_load/gift_auto_load/lib64/python3.6/site-packages/fpdf/fpdf.py", line 1235, in output
    self.close()
  File "/usr/local/home/campuscall/automated/gift_auto_load/gift_auto_load/lib64/python3.6/site-packages/fpdf/fpdf.py", line 322, in close
    self._enddoc()   # close document
  File "/usr/local/home/campuscall/automated/gift_auto_load/gift_auto_load/lib64/python3.6/site-packages/fpdf/fpdf.py", line 1873, in _enddoc
    self._putresources()
  File "/usr/local/home/campuscall/automated/gift_auto_load/gift_auto_load/lib64/python3.6/site-packages/fpdf/fpdf.py", line 1795, in _putresources
    self._putfonts()
  File "/usr/local/home/campuscall/automated/gift_auto_load/gift_auto_load/lib64/python3.6/site-packages/fpdf/fpdf.py", line 1478, in _putfonts
    ttfontstream = ttf.makeSubset(font['ttffile'], subset)
  File "/usr/local/home/campuscall/automated/gift_auto_load/gift_auto_load/lib64/python3.6/site-packages/fpdf/ttfonts.py", line 460, in makeSubset
    with open(file ,'rb') as self.fh:
FileNotFoundError: [Errno 2] No such file or directory: '../font/DejaVuSansCondensed.ttf'

**Comment by selevanm** [comment]
Should mention I am using FPDF2 Version:  2.0.3  and the TTFontFile class is Version:  1.04

**Comment by selevanm** [comment]
When `pickle.load` is called the dictionary value for `font_dict['ttffile'] is modified from an absolute path to the relative path.  When I hard code the path to a known font folder location, removing the relative path, I do not get the exception.

def load_cache(filename):
    """Return unpickled object, or None if cache unavailable"""
    if not filename:
        return None
    try:
        with open(filename, "rb") as fh:
            return pickle.load(fh)
    # File missing, unsupported pickle, etc
    except (IOError, ValueError):
        return None

**Comment by dietervansteenwegen** [comment]
Seemingly have the same issue. `add_font` and `set_font` seems to work with absolute path, but when I use `output` I get a FileNotFoundError, pointing to an incorrect path.

Font is at /home/dieter/repos/bitstream_badge_managment/assets/fonts/BauPro-Bold.ttf but the exception refers to 'fonts/BauPro-Bold.ttf'

**Comment by dietervansteenwegen** [comment]
Although I must mention I am not using `FPDF_FONT_DIR` but using the absolute filepath for `add_font`.
fpdf version 1.7.2
ttfonts is version 1.04

**Comment by Lucas-C** [comment]
PyFPDF is not maintained anymore, you may want to check [PyFPDF/fpdf2](https://github.com/PyFPDF/fpdf2) as its successor, with a 99%-compatible API
