### ISSUE TITLE
Can add font using add_font() and absolute filename, but FileNotFoundError on output().

### ISSUE THREAD

**Issue by dietervansteenwegen** [reingart/pyfpdf#198]
Not sure if this is a duplicate of #127 

fpdf version 1.7.2
ttfonts is version 1.04

I use the `add_font` method with its absolute name `/home/dieter/repos/bitstream_badge_managment/assets/fonts/BauPro-Bold.ttf` This does not raise any exceptions. When I use the `output` method, I get the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dieter/repos/bitstream_badge_managment/src/pdf_creator/pdf_creator.py", line 94, in generate
    self.pdf.output(filename)
  File "/home/dieter/repos/bitstream_badge_managment/venv/lib/python3.8/site-packages/fpdf/fpdf.py", line 1121, in output
    self.close()
  File "/home/dieter/repos/bitstream_badge_managment/venv/lib/python3.8/site-packages/fpdf/fpdf.py", line 262, in close
    self._enddoc()
  File "/home/dieter/repos/bitstream_badge_managment/venv/lib/python3.8/site-packages/fpdf/fpdf.py", line 1709, in _enddoc
    self._putresources()
  File "/home/dieter/repos/bitstream_badge_managment/venv/lib/python3.8/site-packages/fpdf/fpdf.py", line 1654, in _putresources
    self._putfonts()
  File "/home/dieter/repos/bitstream_badge_managment/venv/lib/python3.8/site-packages/fpdf/fpdf.py", line 1347, in _putfonts
    ttfontstream = ttf.makeSubset(font['ttffile'], subset)
  File "/home/dieter/repos/bitstream_badge_managment/venv/lib/python3.8/site-packages/fpdf/ttfonts.py", line 459, in makeSubset
    self.fh = open(file ,'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'fonts/BauPro-Bold.ttf'  
```
Seems like only the last subdirectory is kept.

I don't want to put my font in a subdirectory of my source code.

**Comment by dietervansteenwegen** [comment]
Never mind, just found that I should be using fpdf2.
