### ISSUE TITLE
HTML Link in cell

### ISSUE THREAD

**Issue by JoEdMo** [reingart/pyfpdf#70]
I'm trying to write a cell which includes an external HTML link. I can write a HTML link but this is not within my layout cells.

The following does not work:
```
    pdf.cell(0,0,pdf.write_html('<a href="www.google.com">my link</a>', image_map=None),0,0)
```

Any pointers as to how I can write? My anticipated outcome is a link to our website followed by text for the name, price, etc...

**Comment by JoEdMo** [comment]
Here is my backtrace:
```
Traceback (most recent call last):
  File "/Users/jordanmoore/fpdf/pypdf.py", line 222, in <module>
    pdf.cell(0,0,pdf.write_html('<a href="www.google.com">my link</a>', image_map=None),0,0)
  File "/usr/local/lib/python3.5/site-packages/fpdf/fpdf.py", line 150, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/fpdf/fpdf.py", line 755, in cell
    txt2 = self._escape(txt)
  File "/usr/local/lib/python3.5/site-packages/fpdf/fpdf.py", line 1899, in _escape
    return s.replace('\\','\\\\').replace(')','\\)').replace('(','\\(').replace('\r','\\r')
AttributeError: 'NoneType' object has no attribute 'replace'
```
