### ISSUE TITLE
failed to add certain PNG

### ISSUE THREAD

**Issue by ripples-alive** [reingart/pyfpdf#71]
My code is something like:

```python
from fpdf import FPDF

pdf = FPDF(unit='pt',format=[1058, 1497])
pdf.add_page()
pdf.image('tmpB8jsgj.png')
pdf.output('test.pdf', 'F')
```

Here is the corresponding [image](https://cloud.githubusercontent.com/assets/7439574/18629979/04519c2e-7e9c-11e6-9424-8b0e78b576fb.png).

After running the code, I get an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/fpdf/fpdf.py", line 150, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fpdf/fpdf.py", line 971, in image
    info=self._parsepng(name)
  File "/usr/local/lib/python2.7/site-packages/fpdf/fpdf.py", line 1844, in _parsepng
    f.read(n+4)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by ripples-alive** [comment]
Maybe there are some fields broken for the image, but it would be better if `pyfpdf` can support it as we can open it with normal photo viewer.

**Comment by Scondo** [comment]
This will require complete decoding of png: image data compressed and without uncompressing and interpreting data this file looks like unfinished download.

It's not metadata broken. It's main image data broken. Photo viewer can display picture as it use way "let's try display at least what we have" and lucky "we have" is all image, but only this specific time.

I doubt it would be wise to allow using incomplete files in pdf.
